<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */
                echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */
                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */
                               echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */
                                echo $block->getCustomName() . $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php //if ($_product->getData('call_for_price') == null): ?>
                            <?php /* @escapeNotVerified */
                            echo $block->getProductPrice($_product) ?>
                        <?php //endif; ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div
                                class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div
                                    class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <?php if ($_product->getData('call_for_price') == null): ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                            echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */
                                                echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php endif; ?>

                                        <?php if ($_product->getData('call_for_price') == 1): ?>
                                            <form data-role="callfor-price-form" action="<?php /* @escapeNotVerified */
                                            echo $postParams['action']; ?>" method="post">

                                                <input type="hidden" name="product"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data']['product']; ?>">

                                                <input type="hidden" name="product_name"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $_product->getName(); ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */
                                                echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Call For Price')); ?>"
                                                        class="action callForFree primary">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Call For Price') ?></span>
                                                </button>
                                            </form>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */
                                                    echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                    echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links"
                                     class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php /* @escapeNotVerified */
                                           echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?php /* @escapeNotVerified */
                                                echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php /* @escapeNotVerified */
                                       echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <span><?php /* @escapeNotVerified */
                                            echo __('Add to Compare') ?></span>
                                    </a>
                                </div>
                            </div>
                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                    echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */
                                        echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }





        </script>
    <?php endif; ?>
<?php endif; ?>

<!--Jquery Model for popup of call for free contact form-->
<div id="callForFreeModal">

    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">

            <div class="modal-body">
                <form data-role="callfor-price-form" name="callfor-price-form" id="callfor-price-form"
                      action="<?php /* @escapeNotVerified */
                      echo $block->getUrl('callforprice/index/index') ?>" method="post">
                    <?php echo $block->getBlockHtml('formkey'); ?>
                    <div class="form-group">
                        <label for="firstname">First Name</label>
                        <input type="text" class="form-control"
                               id="firstname" name="first_name" placeholder="First Name"
                               data-validate="{required:true}"/>
                        <input type="hidden" class="form-control"
                               id="product_id"/>
                        <input type="hidden" class="form-control"
                               id="product_name"/>
                    </div>
                    <div class="form-group">
                        <label for="lastname">Last Name</label>
                        <input type="text" class="form-control"
                               id="lastname" name="last_name" placeholder="Last Name"/>
                    </div>
                    <div class="form-group">
                        <label for="InputEmail1">Email address</label>
                        <input type="email" class="form-control"
                               name="email" id="email" placeholder="Enter email"/>
                    </div>

                    <div class="form-group">
                        <label for="detail">Detail</label>
                        <textarea class="form-control" placeholer="Description" name="description"
                                  id="description"></textarea>
                    </div>
                </form>
            </div>

        </div>

    </div>
</div>

<!--juqery to open jquery model and save form by ajax-->
<script>
    var product = 0;
    var product_name = '';
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function ($, modal) {

            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Product Price Enquiry Form',
                buttons: [{
                    text: $.mage.__('Save'),
                    class: '',
                    click: function () {

                        formData = $('#callfor-price-form').serialize() + '&product_id=' + product + '&product_name=' + product_name;
                        jQuery.ajax({
                            url: 'http://magento2-dev.local/callforprice/index/index/',
                            data: formData,
                            type: 'POST'
                        }).done(function (data) {
                            if (data.status == 'success') {
                                alert('Success:')
                            } else {
                                alert('Error:')
                            }

                        });
                        this.closeModal();
                    }
                }]
            };
            var popup = modal(options, $('#callForFreeModal'));
            $(".callForFree").on("click", function (event) {
                event.preventDefault();
                $('#callfor-price-form')[0].reset();
                $('#callForFreeModal').modal('openModal');
                product = $(this).parent().find('input[name=product_id]').val();
                product_name = $(this).parent().find('input[name=product_name]').val();


            });
        }
    );
</script>
