
<div class="log">
<!--   <?php
/*   $data=$this->getLogDetail();

   */?>
   <div class="row">
      <span class="slabel"><strong>Sender:</strong></span>
      <span class="sdescription"><?php /* echo $data['sender'] */?></span>
   </div>
   <div class="row">
      <span class="slabel"><strong>Receiver:</strong></span>
      <span class="sdescription"><?php /* echo $data['receiver'] */?></span>
   </div>
   <div class="row">
      <span class="slabel"><strong>Subject:</strong></span>
      <span class="sdescription"><?php /* echo $data['subject'] */?></span>
   </div>

   <div class="row">
      <span class="slabel"><strong>Template:</strong></span>
      <span class="sdescription"><?php /* echo $data['description'] */?></span>
   </div>-->
   On the view page
</div>
