<?php
/**
 * Created by PhpStorm.
 * User: Harishankar.Malviya
 * Date: 5/3/2016
 * Time: 12:51 PM
 */
namespace Perficient\Gallery\Block\Adminhtml\Images\Edit;

use Magento\Backend\Block\Widget\Form\Generic;

class Form extends Generic
{

    protected function _prepareForm()
    {
        $form = $this->_formFactory->create([
                'data' => [
                    'id' => 'edit_form',
                    'action' => $this->getData('action'),
                    'method' => 'post',
                    'enctype' => 'multipart/form-data'
                ]
            ]

        );
        $form->setUseContainer(true);
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}