<style>
    .simplenews > ul {
        list-style: none;
        padding: 0;
    }
    .simplenews > ul li {
        padding: 10px 5px;
        margin: 0;
        background-color: #fff;
        border-bottom: 1px #c4c1bc solid;
        display: inline-block;
        width: 100%;
    }
    .simplenews > ul li:last-child {
        border-bottom: none;
    }
    .simplenews-list {
        float: left;
        position: relative;
        margin-left: 10px;
        width: 100%;
    }
    .simplenews-list a.news-title {
        font-weight: bold;
    }
    .simplenews-list a.news-title:hover {
        text-decoration: none;
    }
    .block-simplenews .block-title {
        margin: 0px 0px 20px;
    }
    .block-simplenews-heading {
        font-size: 18px;
        font-weight: 300;
    }
</style>
<div class="simplenews">
<?php
$collection =    $collection=$this->getBlogs();
if ($collection->getSize() > 0) :
    ?>
    <div class="toolbar top">
        <?php echo $block->getPagerHtml(); ?>
    </div>

    <ul>
        <?php foreach ($collection as $blog) : ?>
            <li>
                <div class="simplenews-list">
                    <a class="news-title" href="<?php echo $this->getUrl('blogs/view/index',
                        ['blog_id' => $blog->getId()]) ?>"><?php echo $blog->getTitle() ?></a>
                    <div class="simplenews-list-content">
                        <?php echo $blog->getDescription() ?>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>

    <div style="clear: both"></div>

    <div class="toolbar-bottom">
        <div class="toolbar bottom">
            <?php echo $this->getPagerHtml(); ?>
        </div>
    </div>
<?php else : ?>
    <p><?php echo __('Have no article!') ?></p>
<?php endif; ?>
</div>