<?php
/**
 * Created by PhpStorm.
 * User: Harishankar.Malviya
 * Date: 5/6/2016
 * Time: 1:14 PM
 */
?>
<link rel="stylesheet" type="text/css"
      href="<?php echo $block->getViewFileUrl('Perficient_Gallery::css/slider.css'); ?>"/>
<script type="text/javascript" src="<?php echo $block->getViewFileUrl('Perficient_Gallery::js/slider.js'); ?>"></script>
<?php $images = $this->getGalleryData(); ?>
<div class="sliderContainer">
    <h3><a href="#"><?php echo $images['title'] ?></a></h3>
    <ul id="my_slider">
        <?php
        $count = 0;

        foreach ($images['images'] as $val) {

            $url = "http://magento2-dev.local/media/" . $val['image_url']; ?>
            <li><img src="<?php echo $url; ?>" alt=""/></li>
            <?php $count++;
        } ?>
    </ul>
    <div id="counter"></div>
</div>


