<?php
/**
 * Created by PhpStorm.
 * User: Harishankar.Malviya
 * Date: 5/6/2016
 * Time: 1:14 PM
 */
?>
<?php $images = $this->getGalleryData();
if (!empty($images['images'])) { ?>
<link rel="stylesheet" type="text/css"
      href="<?php echo $block->getViewFileUrl('Perficient_Gallery::css/slider.css'); ?>"/>
<script type="text/javascript" src="<?php echo $block->getViewFileUrl('Perficient_Gallery::js/slider.js'); ?>"></script>

    <div class="sliderContainer">
        <h3><a href="#"><?php echo !empty($images['title']) ? $images['title'] : '' ?></a></h3>
        <ul id="my_slider">
            <?php
            $count = 0;

            foreach ($images['images'] as $val) {

                $url = "http://magento2-dev.local/media/" . !empty($val['image_url']) ? $val['image_url'] : ''; ?>
                <li><img src="<?php echo $url; ?>" alt=""/></li>
                <?php $count++;
            }

            ?>
        </ul>
        <div id="counter"></div>
    </div>
<?php } ?>

