<?php
namespace Perficient\Gallery\Block\Adminhtml\Images\Edit\Tab;

use Magento\Backend\Block\Template\Context;
use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Magento\Framework\Data\FormFactory;
use Magento\Framework\Registry;
use Magento\Store\Model\System\Store;
use Perficient\Gallery\Model\Status;

class ImageInfo extends Generic implements TabInterface
{
    protected $_status;
    protected $_buttonlist;
    protected $_storeManager;
    /**
     * @var \Magento\Store\Model\System\Store
     */
    protected $_store;


    public function __construct(
        Context $context,
        Registry $registry,
        FormFactory $formFactory,
        Status $status,
        \Magento\Backend\Block\Widget\Button\ButtonList $buttonList,
        Store $store,
        array $data = []
    )
    {
        $this->_status = $status;
        $this->_buttonlist = $buttonList;
        $this->_storeManager = $context->getStoreManager();
        $this->_store = $store;
        parent::__construct($context, $registry, $formFactory, $data);

    }

    /**
     * Prepare label for tab
     *
     * @return string
     */
    public function getTabLabel()
    {
        return __('Image Info');
    }

    /**
     * Prepare title for tab
     *
     * @return string
     */
    public function getTabTitle()
    {
        return __('Image Info');
    }

    /**
     * {@inheritdoc}
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isHidden()
    {
        return false;
    }

    protected function _prepareForm()
    {

        $model = $this->_coreRegistry->registry('image_data');
        $form = $this->_formFactory->create();
        $fieldSet = $form->addFieldset(
            'base_fieldset',
            ['legent' => __('General')]
        );
        if ($model->getImageId()) {
            $fieldSet->addField(
                'image_id',
                'hidden',
                ['name' => 'image_id']
            );
        }
        $fieldSet->addField(
            'image_url',
            'image',
            [
                'title' => __('Image'),
                'label' => __('Image'),
                'name' => 'image_url',
                'class' => 'required-entry required-file',
                'required' => true,
                'note' => 'Allow image type: jpg, jpeg, gif, png',
            ]
        );

        $fieldSet->addField(
            'description',
            'textarea',
            [
                'title' => __('Description'),
                'label' => __('Description'),
                'name' => 'description',
                'class' => 'required-entry required-file',
                'required' => true,
            ]
        );

        $fieldSet->addField(
            'url',
            'text',
            [
                'title' => __('URL'),
                'label' => __('URL'),
                'name' => 'page_url',
                'class' => 'required-entry required-file',
                'required' => true,
            ]
        );
      
        $fieldSet->addField(
            'status',
            'select',
            [
                'name' => 'status',
                'label' => __('Status'),
                'options' => $this->_status->getOptionArray()
            ]
        );


        $data = $model->getData();
        $form->setValues($data);
        $this->setForm($form);

        return parent::_prepareForm();

        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}
